name: Reusable CI Steps

# This workflow is triggered by other workflows
on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-test:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages (PR / push)
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
        # if this is called in contexts without a PR, the action will still check commits in the push

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm format --check

      - name: Run linter
        run: pnpm lint

      - name: Run test coverage
        run: pnpm test:coverage

      - name: Build
        run: pnpm build